config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root 'static_pages#home'
  # match '/signup', to: 'parents#new', via: 'get'
  match '/coach_profiles', to: 'static_pages#coach_profiles', via: 'get'

### Parents ###
  devise_for :parents

  resources :parents do
    resources :players
    resources :camp_registrations
    resources :charges
  end

  resources :camps do
    resources :camp_sessions
    resources :locations
  end

  resources :players, :only => [:show] do
    resources :camp_sessions, :through => :camps
    resources :registrations
  end

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :email, :presence => true
  validates :password, :presence => true
end

app/models/camp.rb
class Camp < ActiveRecord::Base

  has_many :camp_sessions
  belongs_to :location

  validates :name, :presence => true
  validates :description, :presence => true
  validates :num_of_attendees, :presence => true

  def start_time
    camp_sessions.order(:start_time => :asc).first.start_time
  end


  def end_time
    camp_sessions.order(:end_time => :desc).first.end_time
  end

end

app/models/camp_registration.rb
class CampRegistration < ActiveRecord::Base
  belongs_to :player
  belongs_to :camp_session
  belongs_to :parent

  validates :player_id, :presence => true
  validates :camp_session_id, :presence => true
  validates :parent_id, :presence => true

  scope :for_parent, ->(parent) { where(:parent => parent) }

end

app/models/camp_session.rb
class CampSession < ActiveRecord::Base
  belongs_to :camp
  has_many :camp_registrations
  has_many :players, :through => :camp_registrations

  validates :title, :presence => true
  validates :description, :presence => true
  validates :start_time, :presence => true
  validates :end_time, :presence => true
  validates :price, :presence => true

  scope :earliest, -> { order("start_time ASC").first }
  scope :chronological, -> {order("start_time ASC") }

  def title_with_start_date
    @title_with_start_date = "#{camp.name} - #{start_time.strftime('%A, %d %b %Y')}"
  end
end

app/models/charge.rb
class Charge < ActiveRecord::Base
  belongs_to :parent
  validates :parent_id, :presence => true
end

app/models/coach.rb
class Coach < ActiveRecord::Base
  validates :first_name, presence: true, length: { maximum: 50 }
  validates :last_name, presence: true, length: { maximum: 50}
  validates :bio, presence: true

  def fullname
    "#{first_name.titleize} #{last_name.titleize}"
  end
end

app/models/location.rb
class Location < ActiveRecord::Base
  has_one :camp

  validates :name, :presence => true
end

app/models/parent.rb
class Parent < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :players
  has_many :camp_registrations
  has_many :charges

  validates :first_name, :presence => true
  validates :last_name, :presence => true
  validates :email, :presence => true
  validates :password, :presence => true
  validate :presence_of_phone_number

  def full_name
    "#{first_name.titleize} #{last_name.titleize}"
  end

  def presence_of_phone_number
    if mobile_number.blank? && home_phone_number.blank?
      errors.add(:mobile_phone_number, 'or Home phone number must be supplied')
    end
  end

  def camp_registrations_total_price
    camp_registrations.inject(0) {|sum, cr| sum + cr.camp_session.price }
  end

end

app/models/player.rb
class Player < ActiveRecord::Base

  belongs_to :parent
  belongs_to :standard
  has_many :camp_registrations
  has_many :camp_sessions, :through => :camp_registrations

  validates :first_name, :presence => true
  validates :last_name, :presence => true
  validates :dob, :presence => true
  validates :standard, :presence => true
  validates :gender, :presence => true
  validates :parent, :presence => true

  def full_name
    @player = "#{first_name.titleize} #{last_name.titleize}"
  end

end

app/models/registration.rb
class Registration < ActiveRecord::Base
  belongs_to :player
  belongs_to :camp_session
end

app/models/standard.rb
class Standard < ActiveRecord::Base
  has_many :players
  validates :level, :presence => :true
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
end

app/controllers/camps_controller.rb
class CampsController < ApplicationController

  def index
    @camps = Camp.includes(:camp_sessions).all
  end

  def show
    @camp = Camp.includes(:camp_sessions).find(params[:id])
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new
    @crs = CampRegistration.for_parent(current_parent)
    @amount =  current_parent.camp_registrations_total_price.to_i
  end

  def create
    customer_email = current_parent.email
    @amount =  current_parent.camp_registrations_total_price.to_i
    customer = Stripe::Customer.create(
      :email => customer_email,
      :card => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer => customer.id,
      :amount => @amount,
      :description => 'description',
      :currency => 'gbp'
    )

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to parent_charge_path(current_parent)
  end

end

app/controllers/coaches_controller.rb
class CoachesController < ApplicationController

  def index
    @coaches = coach.paginate(page: params[:page])
  end

  def new
    @coach = Coach.new
  end

  def create
    @coach = Coach.new(coach_params)
    if @coach.save
      flash[:success] = "Thank you for registering."
      redirect_to root_url
    else
      render 'new'
    end
  end

  def show
    @coach = Coach.find(params[:id])
    @microposts = @coach.microposts.paginate(:page => params[:page])
  end

  def edit
  end

  def update
    if @coach.update_attributes(coach_params)
      flash[:success] = "Profile updated"
      redirect_to @coach
    else
      render 'edit'
    end
  end

  def destroy
    @coach = Coach.find(params[:id])
    @coach.destroy unless @coach == current_coach
    flash[:success] = "#{@coach.name} has been deleted"
    redirect_to coaches_url
  end

  private

  def coach_params
    params.require(:coach).permit(
      :firstname, :lastname, :bio, :gravatar, :password, :password_confirmation)
  end

end

app/controllers/parents_controller.rb
class ParentsController < ApplicationController
  def show
    @parent = Parent.find(params[:id])
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_filter :set_associations, :only => [:new, :create]

  def new
    @player = Player.new
  end

  def create
    @player = Player.new(player_params)
    @player.parent = @parent
    if @player.save
      flash[:notice] = 'Player added'
      redirect_to parent_path(current_parent)
    else
      render :action => :new
    end
  end

  private

  def player_params
    params[:player].permit(:first_name, :last_name, :dob, :club, :gender,
      :medical, :allergies, :standard_id, parent_attributes: [:parent_id])
  end

  def set_associations
    @standards = Standard.all
    @parent = current_parent
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @camp = CampSession.earliest.camp
  end

  def coach_profiles
    @coaches = Coach.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title)
    base_title = "Hockey Akademy"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end

  def full_name(first, last)
    "#{first.titleize} #{last.titleize}"
  end

  def format_date(date)
    date.strftime('%A, %d %b %Y')
  end

  def format_time(time)
    time.strftime("%A, %d %b %Y %l:%M %p")
  end
end

app/helpers/camp_registrations_helper.rb
# encoding: UTF-8
module CampRegistrationsHelper

  def total(camp_registrations)
    total = camp_registrations.inject(0) {|sum,cr| sum + cr.camp_session.price}
    number_to_currency(total, :unit => "£")
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/static_pages/coach_profiles.html.erb
<% provide(:title, 'Coaches Profiles') %>
<%= render 'shared/register_camp_link'  %>
<h2>Coaches Profiles</h2>
<% if @coaches.empty? %>
  <p>We are in the process of building this page, please check back soon.</p>
<% else %>
  <ul class="coach-list">
    <% @coaches.each do |coach| %>
      <li>
        <%= image_tag("#{coach.gravatar}", size: "150x150") %>
        <div class="coach-text">
          <h3><%= coach.fullname %></h3>
          <p><%= coach.bio %></p>
        </div>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/static_pages/home.html.erb
<% provide(:title, '') %>
<%= link_to_if(current_parent.nil?, "Sign in / Sign up to book a camp", new_parent_session_path) do
     link_to('Book a camp', new_parent_camp_registration_path(current_parent), :class => "btn btn-primary")
   end
  %>
<div id="wrapper">
  <h2>Next Camp: <%= @camp.name %></h2>
  <p>Starts <%= format_date(@camp.start_time) %>
  <%= link_to 'Details', camp_path(@camp) %></p>

  <div class="slider-wrapper theme-default">
    <div class="ribbon"></div>
      <div id="slider">
        <%= image_tag "image1400.jpg" %>
        <%= image_tag "image2400.jpg" %>
        <%= image_tag "image3400.jpg" %>
        <%= image_tag "image4400.jpg" %>
      </div>
    </div>
  </div>
</div>
<script>
  $(window).load(function(){
    $('#slider').ramblingSlider({
      'effect': 'fade',
      'speed' : 1000,
      'pauseTime' : 3000
    });
  });
</script>
<div>
  <%= link_to "Sign up", new_parent_registration_path, class: 'btn btn-large btn-primary' %>
</div>

app/views/static_pages/register.html.erb
<% provide(:title, 'Registration') %>
<h2>Registration</h2>
<form>
  <fieldset>
    <%= collection_select(:camp_session, :camp_session_id, @camp_sessions, :id, :title_with_start_date, {prompt: 'Select a session(s)'}, { :multiple => true }) %>
    <%= collection_select(:player, :player_id, @players, :id, :full_name, {prompt: 'Select a player'}, { :multiple => false }) %>
  </fieldset>
  <div class="submit">
    <%= link_to 'Book', new_player_camp_session_path, :class => "btn btn-primary" %>
  </div> <!-- div.submit -->
</form>