config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root 'static_pages#home'
  # match '/signup', to: 'parents#new', via: 'get'
  match '/coach_profiles', to: 'static_pages#coach_profiles', via: 'get'

### Parents ###
  devise_for :parents

  resources :parents do
    resources :players
    resources :camp_registrations
    resources :charges
  end

  resources :camps do
    resources :camp_sessions
    resources :locations
  end

  resources :players, :only => [:show] do
    resources :camp_sessions, :through => :camps
    resources :registrations
  end

end

app/models/charge.rb
class Charge < ActiveRecord::Base
  belongs_to :parent
  validates :parent_id, :presence => true
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new
    @crs = CampRegistration.for_parent(current_parent)
    @amount =  current_parent.camp_registrations_total_price.to_i
  end

  def create
    customer_email = current_parent.email
    @amount =  current_parent.camp_registrations_total_price.to_i
    customer = Stripe::Customer.create(
      :email => customer_email,
      :card => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer => customer.id,
      :amount => @amount,
      :description => 'description',
      :currency => 'gbp'
    )

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to parent_charge_path(current_parent)
  end

end

app/views/charges/create.html.erb
<p>Thank you</p>

app/views/charges/new.html.erb
<%= form_tag parent_charges_path(current_parent) do %>
  <section>
    <%= render 'shared/details' %>
  </section>
  <article>
    <label class="amount">
      <span>Amount: <%= number_to_currency(@amount, {:unit => '£'}) %></span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= ENV['STRIPE_PUBLISHABLE_KEY'] %>"
          data-description="A month's subscription"
          data-amount= <%= "#{@amount * 100}" %>
          data-currency="GBP">
          </script>
<% end %>