config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root 'static_pages#home'
  # match '/signup', to: 'parents#new', via: 'get'
  match '/coach_profiles', to: 'static_pages#coach_profiles', via: 'get'

### Parents ###
  devise_for :parents

  resources :parents do
    resources :players
    resources :camp_registrations
    resources :charges
  end

  resources :camps do
    resources :camp_sessions
    resources :locations
  end

  resources :players, :only => [:show] do
    resources :camp_sessions, :through => :camps
    resources :registrations
  end

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :email, :presence => true
  validates :password, :presence => true
end

app/models/camp.rb
class Camp < ActiveRecord::Base

  has_many :camp_sessions
  belongs_to :location

  validates :name, :presence => true
  validates :description, :presence => true
  validates :num_of_attendees, :presence => true

  def start_time
    camp_sessions.order(:start_time => :asc).first.start_time
  end


  def end_time
    camp_sessions.order(:end_time => :desc).first.end_time
  end

end

app/models/camp_registration.rb
class CampRegistration < ActiveRecord::Base
  belongs_to :player
  belongs_to :camp_session
  belongs_to :parent

  validates :player_id, :presence => true
  validates :camp_session_id, :presence => true
  validates :parent_id, :presence => true

  scope :for_parent, ->(parent) { where(:parent => parent) }

end

app/models/camp_session.rb
class CampSession < ActiveRecord::Base
  belongs_to :camp
  has_many :camp_registrations
  has_many :players, :through => :camp_registrations

  validates :title, :presence => true
  validates :description, :presence => true
  validates :start_time, :presence => true
  validates :end_time, :presence => true
  validates :price, :presence => true

  scope :earliest, -> { order("start_time ASC").first }
  scope :chronological, -> {order("start_time ASC") }

  def title_with_start_date
    @title_with_start_date = "#{camp.name} - #{start_time.strftime('%A, %d %b %Y')}"
  end
end

app/models/charge.rb
class Charge < ActiveRecord::Base
  belongs_to :parent
  validates :parent_id, :presence => true
end

app/models/coach.rb
class Coach < ActiveRecord::Base
  validates :first_name, presence: true, length: { maximum: 50 }
  validates :last_name, presence: true, length: { maximum: 50}
  validates :bio, presence: true

  def fullname
    "#{first_name.titleize} #{last_name.titleize}"
  end
end

app/models/location.rb
class Location < ActiveRecord::Base
  has_one :camp

  validates :name, :presence => true
end

app/models/parent.rb
class Parent < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :players
  has_many :camp_registrations
  has_many :charges

  validates :first_name, :presence => true
  validates :last_name, :presence => true
  validates :email, :presence => true
  validates :password, :presence => true
  validate :presence_of_phone_number

  def full_name
    "#{first_name.titleize} #{last_name.titleize}"
  end

  def presence_of_phone_number
    if mobile_number.blank? && home_phone_number.blank?
      errors.add(:mobile_phone_number, 'or Home phone number must be supplied')
    end
  end

  def camp_registrations_total_price
    camp_registrations.inject(0) {|sum, cr| sum + cr.camp_session.price }
  end

end

app/models/player.rb
class Player < ActiveRecord::Base

  belongs_to :parent
  belongs_to :standard
  has_many :camp_registrations
  has_many :camp_sessions, :through => :camp_registrations

  validates :first_name, :presence => true
  validates :last_name, :presence => true
  validates :dob, :presence => true
  validates :standard, :presence => true
  validates :gender, :presence => true
  validates :parent, :presence => true

  def full_name
    @player = "#{first_name.titleize} #{last_name.titleize}"
  end

end

app/models/registration.rb
class Registration < ActiveRecord::Base
  belongs_to :player
  belongs_to :camp_session
end

app/models/standard.rb
class Standard < ActiveRecord::Base
  has_many :players
  validates :level, :presence => :true
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
end

app/controllers/camps_controller.rb
class CampsController < ApplicationController

  def index
    @camps = Camp.includes(:camp_sessions).all
  end

  def show
    @camp = Camp.includes(:camp_sessions).find(params[:id])
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new
    @crs = CampRegistration.for_parent(current_parent)
    @amount =  current_parent.camp_registrations_total_price.to_i
  end

  def create
    customer_email = current_parent.email
    @amount =  current_parent.camp_registrations_total_price.to_i
    customer = Stripe::Customer.create(
      :email => customer_email,
      :card => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer => customer.id,
      :amount => @amount,
      :description => 'description',
      :currency => 'gbp'
    )

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to parent_charge_path(current_parent)
  end

end

app/controllers/coaches_controller.rb
class CoachesController < ApplicationController

  def index
    @coaches = coach.paginate(page: params[:page])
  end

  def new
    @coach = Coach.new
  end

  def create
    @coach = Coach.new(coach_params)
    if @coach.save
      flash[:success] = "Thank you for registering."
      redirect_to root_url
    else
      render 'new'
    end
  end

  def show
    @coach = Coach.find(params[:id])
    @microposts = @coach.microposts.paginate(:page => params[:page])
  end

  def edit
  end

  def update
    if @coach.update_attributes(coach_params)
      flash[:success] = "Profile updated"
      redirect_to @coach
    else
      render 'edit'
    end
  end

  def destroy
    @coach = Coach.find(params[:id])
    @coach.destroy unless @coach == current_coach
    flash[:success] = "#{@coach.name} has been deleted"
    redirect_to coaches_url
  end

  private

  def coach_params
    params.require(:coach).permit(
      :firstname, :lastname, :bio, :gravatar, :password, :password_confirmation)
  end

end

app/controllers/parents_controller.rb
class ParentsController < ApplicationController
  def show
    @parent = Parent.find(params[:id])
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_filter :set_associations, :only => [:new, :create]

  def new
    @player = Player.new
  end

  def create
    @player = Player.new(player_params)
    @player.parent = @parent
    if @player.save
      flash[:notice] = 'Player added'
      redirect_to parent_path(current_parent)
    else
      render :action => :new
    end
  end

  private

  def player_params
    params[:player].permit(:first_name, :last_name, :dob, :club, :gender,
      :medical, :allergies, :standard_id, parent_attributes: [:parent_id])
  end

  def set_associations
    @standards = Standard.all
    @parent = current_parent
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title)
    base_title = "Hockey Akademy"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end

  def full_name(first, last)
    "#{first.titleize} #{last.titleize}"
  end

  def format_date(date)
    date.strftime('%A, %d %b %Y')
  end

  def format_time(time)
    time.strftime("%A, %d %b %Y %l:%M %p")
  end
end

app/helpers/camp_registrations_helper.rb
# encoding: UTF-8
module CampRegistrationsHelper

  def total(camp_registrations)
    total = camp_registrations.inject(0) {|sum,cr| sum + cr.camp_session.price}
    number_to_currency(total, :unit => "£")
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Website by <%= link_to 'margOnline', 'http://margonline.co.uk' %>
  </small>
</footer>

app/views/layouts/_header.html.erb
<header id="site-header" class="site-head" role="banner">
  <%= link_to image_tag("logo_sml.png", alt: "logo"), root_path %>
  <div id="site-logo"><%= BRAND_NAME %></div>
  <div class="container">
    <nav class="site-nav">
      <ul>
        <li><%= link_to "Coach Profiles", coach_profiles_path %></li>
        <% if current_parent %>
          <li><%= link_to 'Camps', camps_path %></li>
          <li><%= link_to 'Sign out', destroy_parent_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign up", new_parent_registration_path %></li>
          <li><%= link_to 'Sign in', new_parent_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %> </title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <link href='http://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
    <%= csrf_meta_tags %>
   <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |k,v| %>
        <div class="alert alert-<%= k %>"><%= v %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer'  %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_basket_link.html.erb
<div class="cta">
  <%= link_to image_tag('cart.jpg',:alt => 'cart'), new_parent_charge_path, :parent_id => current_parent.id %>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |message| %>
      <li>* <%= message %></li>
      <li><% p object.inspect %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_payment_link.html.erb
<div class="cta">
  <%= link_to 'Pay', new_parent_charge_path(current_parent), :class => 'btn btn-primary' %>
</div>

app/views/shared/_register_camp_link.html.erb
<div class="cta">
  <% if current_parent %>
    <%= link_to "Register", new_parent_camp_registration_path(current_parent.id), :class => 'btn btn-primary' %>
  <% else %>
    <%= link_to "You must have an account to register for a camp", new_parent_registration_path, :class => 'btn btn-primary' %>
  <% end %>
</div>